BitirmeProjesi/Models/Participant.cs
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace BitirmeProjesi.Models
{
    public class Participant
    {
        [Key]
        public int Id { get; set; }

        public int PeriodId { get; set; }
        public int StudentId { get; set; }
        public string Subject { get; set; } = null!;

        // 0=> Yeni Kayıt,1=>Kabul Edildi ,2=>Reddedildi
        public byte? AdvisorStatus { get; set; }

        public DateTime CreateAt { get; set; }

        [ForeignKey("PeriodId")]
        public Period Period { get; set; } = null!;

        [ForeignKey("StudentId")]
        public Student Student { get; set; } = null!;

        public virtual List<ParticipantTeacher>? ParticipantTeachers { get; set; }
    }
}

BitirmeProjesi/Areas/Admin/Controllers/AcademianController.cs
using BitirmeProjesi.Data;
using BitirmeProjesi.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Linq;

namespace BitirmeProjesi.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize]
    public class AcademianController : Controller
    {
        private readonly BitirmeDBContext _context;

        public AcademianController(BitirmeDBContext context)
        {

            _context = context;
        }

        public IActionResult Index()
        {
            User CurrentUser = _context.Users.Where(x => x.UserName == this.HttpContext.User.Identity.Name).FirstOrDefault();


            string Sql = "Select Periods.* from Periods " +
                "Left Join Participants on Participants.PeriodId = Periods.Id " +
                "Left Join ParticipantTeachers on ParticipantTeachers.ParticipantId = Participants.Id " +
                "Where ParticipantTeachers.TeacherId =  " + CurrentUser.Id +
                "Group by Periods.Id,Periods.Name,Periods.StartAt,Periods.FinishAt,Periods.CreateUserId,Periods.CreateAt";

            List<Period> result = _context.Periods.FromSqlRaw(Sql).ToList();


            return View(result);
        }

        public async Task<IActionResult> Details(int? id)
        {
            User CurrentUser = _context.Users.Where(x => x.UserName == this.HttpContext.User.Identity.Name).FirstOrDefault();
            ViewData["CurrentUser"] = CurrentUser;

            if (id == null)
            {
                return NotFound();
            }

            Period period = await _context
                .Periods
                .Include(p => p.CreateUser)
                .Include(p => p.Participants)
                .Include("Participants.Student")
                .Include("Participants.ParticipantTeachers")
                .Include("Participants.ParticipantTeachers.Teacher")
                .FirstOrDefaultAsync(m => m.Id == id);

            if (period == null)
            {
                return NotFound();
            }

            return View(period);
        }

        public async Task<IActionResult> Participants(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            User CurrentUser = _context.Users.Where(x => x.UserName == this.HttpContext.User.Identity.Name).FirstOrDefault();
            ViewData["CurrentUser"] = CurrentUser;

            ViewBag.Message = TempData["Message"];

            Period period = await _context
                .Periods
                .Include(p => p.CreateUser)
                .Include(p => p.Participants)
                .Include("Participants.Student")
                .Include("Participants.ParticipantTeachers")
                .Include("Participants.ParticipantTeachers.Teacher")
                .FirstOrDefaultAsync(m => m.Id == id);

            if (period == null)
            {
                return NotFound();
            }

            return View(period);
        }

        public IActionResult Accept(int id)
        {
            ParticipantTeacher model = this._context.ParticipantTeachers.Include(x => x.Participant).Include(y => y.Teacher).Where(z=>z.Id == id).FirstOrDefault();

            if (model == null)
            {
                return NotFound();
            }

            int onaySayisi = _context.ParticipantTeachers.Count(pt => pt.TeacherId == model.TeacherId && pt.Status == 1 && pt.Participant.PeriodId == model.Participant.PeriodId);
            if (model.Teacher.Quota > onaySayisi)
            {

                model.Status = 1;
                this._context.Update(model);

            }
            else
            {
                ViewBag.Message = "Kota dolu.";
            }
            this._context.SaveChanges();

            TempData["Message"] = ViewBag.Message;
            return RedirectToAction("Participants", new { id = model.Participant.PeriodId, message = ViewBag.Message });

        }


        public IActionResult Reject(int id)
        {
            var model = this._context.ParticipantTeachers.Find(id);

            model.Status = 2;
            this._context.Update(model);
            this._context.SaveChanges();

            if (model != null)
            {
                var participantId = model.ParticipantId;
                var participant = _context.Participants.FirstOrDefault(p => p.Id == participantId);
                if (participant != null)
                {
                    var periodId = participant.PeriodId;
                    var period = _context.Periods.FirstOrDefault(p => p.Id == periodId);
                    if (period != null)
                    {
                        return RedirectToAction("Participants", new { id = period.Id });
                    }
                }
            }

            return RedirectToAction("Index");
        }
    }
}

BitirmeProjesi/Areas/Admin/Controllers/ChatController.cs
using BitirmeProjesi.Data;
using BitirmeProjesi.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using BitirmeProjesi.Services;

namespace BitirmeProjesi.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize]
    public class ChatController : Controller
    {
        private readonly BitirmeDBContext _context;
        private readonly MailService _mailService;

        public ChatController(BitirmeDBContext context, MailService mailService)
        {
            _context = context;
            _mailService = mailService;
        }

        public IActionResult Index(int id)
        {
            User CurrentUser = _context.Users.Where(x => x.UserName == this.HttpContext.User.Identity.Name).FirstOrDefault();

            Chat chat = this._context.Chats
                .Include("Student")
                .Include("User")
                .Include("ChatMessages")
                .Include("ChatMessages.User")
                .Include("ChatMessages.Student")
                .Where(x => x.UserId == CurrentUser.Id && x.StudentId == id)
                .FirstOrDefault();

            if (chat == null)
            {
                chat = new Chat();
                chat.CreateAt = DateTime.Now;
                chat.StudentId = id;
                chat.UserId = CurrentUser.Id;

                this._context.Chats.Add(chat);

                this._context.SaveChanges();

                return RedirectToAction("Create", new { id = id });
            }


            return View(chat);
        }

        [HttpPost]
        public IActionResult Create([Bind("ChatId,UserId,MessageBody")] ChatMessage chatMessage)
        {
            chatMessage.CreateAt = DateTime.Now;

            _context.Add(chatMessage);
            _context.SaveChanges();
           
            Chat chat = _context.Chats.FirstOrDefault(x => x.Id == chatMessage.ChatId);
            User user = _context.Users.FirstOrDefault(x => x.Id == chat.UserId);
            BitirmeProjesi.Models.Student student = _context.Students.FirstOrDefault(x => x.Id == chat.StudentId);


            string subject = "Yeni Mesaj";
            string body = $"Hocanız size yeni bir mesaj gönderdi: {chatMessage.MessageBody}";

            _mailService.SendEmail(student.Email, subject, body);

            return Redirect(Request.Headers["Referer"].ToString());
        }

    }

}

BitirmeProjesi/Areas/Student/Controllers/ParticipantController.cs
using BitirmeProjesi.Areas.Student.Models.Dto;
using BitirmeProjesi.Data;
using BitirmeProjesi.Models;
using BitirmeProjesi.Models.Dto;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace BitirmeProjesi.Areas.Student.Controllers
{
    [Area("Student")]
    public class ParticipantController : BaseController
    {

        private readonly BitirmeDBContext _context;

        public ParticipantController(BitirmeDBContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            int StudentId = this.getStudentID();

            var participants = _context.Participants
                .Include(y => y.Period)
                .Include(z => z.ParticipantTeachers)
                .Include(z => z.ParticipantTeachers)
                .Include("ParticipantTeachers.Teacher")
                .Where(x => x.StudentId == StudentId)
                .ToList();

            return View(participants);
        }

    }
}

BitirmeProjesi/Areas/Admin/Views/Academian/Details.cshtml
@using BitirmeProjesi.Models;
@model Period

@{
    User CurrentUser = (User)ViewData["CurrentUser"];
}

<h2 class="page-header">Dönem Detayı</h2>

<div class="panel panel-primary">
    <div class="panel-heading">
        Genel Bilgiler
    </div>
    <div class="panel-body">
        <div class="row">
            <div class="col-md-6">
                <table class="table table-striped table-bordered table-hover">
                    <tbody>
                        <tr>
                            <td>ID</td>
                            <td>@Model.Id</td>
                        </tr>
                        <tr>
                            <td>Dönem Adı</td>
                            <td>@Model.Name</td>
                        </tr>
                        <tr>
                            <td>Başlangıç</td>
                            <td>@Model.StartAt</td>
                        </tr>
                        <tr>
                            <td>Bitiş</td>
                            <td>@Model.FinishAt</td>
                        </tr>
                    </tbody>
                </table>
            </div>
            <div class="col-md-6">
                <table class="table table-striped table-bordered table-hover">
                    <tbody>
                        <tr>
                            <td>Oluşturan Kullanıcı</td>
                            <td>@Model.CreateUser.FullName()</td>
                        </tr>
                        <tr>
                            <td>Kayıt Tarihi</td>
                            <td>@Model.CreateAt</td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

<div class="panel panel-primary">
    <div class="panel-heading">
        Kabul Gören  Öğrenci Listeniz
    </div>
    <div class="panel-body">
        <table class="table table-striped table-bordered table-hover">
            <tr>
                <td>ID</td>
                <td>Öğrenci No</td>
                <td>Öğrenci Ad</td>
                <td>Öğrenci Soyad</td>
                <td>Konu</td>
                <td style="width:200px;"></td>
            </tr>
            <tbody>
                @foreach (var item in Model.Participants)
                {
                    if (item.AdvisorStatus == 1)
                    {
                        foreach (var participantTeacher in item.ParticipantTeachers)
                        {
                            if (participantTeacher.TeacherId == CurrentUser.Id && participantTeacher.Status == 1)
                            {
                                <tr>
                                    <td>@item.Id</td>
                                    <td>@item.Student.StudentNumber</td>
                                    <td>@item.Student.Name</td>
                                    <td>@item.Student.Surname</td>
                                    <td>@item.Subject</td>
                                    <td class="text-center">
                                        <a asp-area="Admin" asp-controller="Chat" asp-action="Index" asp-route-id="@item.StudentId" class="btn btn-sm btn-primary">
                                            Mesaj Gönder
                                        </a>
                                    </td>
                                </tr>
                            }
                        }
                    }
                }
            </tbody>
        </table>
    </div>
</div>

BitirmeProjesi/Areas/Admin/Views/Academian/Index.cshtml
<h1 class="page-header">
    Dönem Listesi
</h1>
@model List<BitirmeProjesi.Models.Period>

<div class="table-responsive">
    <table class="table table-striped table-bordered table-hover mt-10" style="margin-top:10px;">
        <tr>
            <th>Ad</th>
            <th>Bitiş Tarihi</th>
            <th></th>
        </tr>
        @foreach (var period in Model)
        {
            <tr>
                <td>@period.Name</td>
                <td>@period.FinishAt</td>
                <td class="text-center">
                    <a asp-action="Details" asp-route-id="@period.Id" class="btn btn-sm btn-primary">
                        Detay
                    </a>

                    <a asp-action="Participants" asp-route-id="@period.Id" class="btn btn-sm btn-primary">
                        Talep Listesi
                    </a>
                </td>
            </tr>
        }
    </table>
</div>

BitirmeProjesi/Areas/Admin/Views/Academian/Participants.cshtml
@using BitirmeProjesi.Models;
@model Period
@inject BitirmeProjesi.Services.ParticipantService ParticipantService;

@{
    User CurrentUser = (User)ViewData["CurrentUser"];
}

<h2 class="page-header">Dönem Detayı</h2>

<div class="panel panel-primary">
    <div class="panel-heading">
        Dönem Detayı
    </div>
    <div class="panel-body">
        <div class="row">
            <div class="col-md-6">
                <table class="table table-striped table-bordered table-hover">
                    <tbody>
                        <tr>
                            <td>ID</td>
                            <td>@Model.Id</td>
                        </tr>
                        <tr>
                            <td>Dönem Adı</td>
                            <td>@Model.Name</td>
                        </tr>
                        <tr>
                            <td>Başlangıç</td>
                            <td>@Model.StartAt</td>
                        </tr>
                        <tr>
                            <td>Bitiş</td>
                            <td>@Model.FinishAt</td>
                        </tr>
                    </tbody>
                </table>
            </div>
            <div class="col-md-6">
                <table class="table table-striped table-bordered table-hover">
                    <tbody>
                        <tr>
                            <td>Oluşturan Kullanıcı</td>
                            <td>@Model.CreateUser.FullName()</td>
                        </tr>
                        <tr>
                            <td>Kayıt Tarihi</td>
                            <td>@Model.CreateAt</td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

<div class="panel panel-primary">
    <div class="panel-heading">
        Onay Bekleyen Öğrenciler
    </div>
    <div class="panel-body">
        <table class="table table-striped table-bordered table-hover">
            <tr>
                <td>ID</td>
                <td>Öğrenci No</td>
                <td>Öğrenci Ad</td>
                <td>Öğrenci Soyad</td>
                <td>Akademisyen</td>
                <td>Konu</td>
            </tr>
            <tbody>
                @foreach (var item in Model.Participants)
                {
                    if (item.AdvisorStatus == 1)
                    {
                        Tuple<ParticipantTeacher, bool> tuple = ParticipantService.Display( CurrentUser.Id, item.ParticipantTeachers);

                        if (tuple.Item2)
                        {
                            <tr>
                                <td>@item.Id</td>
                                <td>@item.Student.StudentNumber</td>
                                <td>@item.Student.Name</td>
                                <td>@item.Student.Surname</td>
                                <td>@tuple.Item1.Teacher.FullName()</td>
                                <td>@item.Subject</td>
                                <td class="text-center">
                                    <a class="btn btn-success btn-sm" asp-area="Admin" asp-controller="Academian" asp-action="Accept" asp-route-id="@tuple.Item1.Id">
                                        Onayla
                                    </a>
                                    <a class="btn btn-danger btn-sm" asp-area="Admin" asp-controller="Academian" asp-action="Reject" asp-route-id="@tuple.Item1.Id">
                                        Reddet
                                    </a>
                                    @if (!string.IsNullOrEmpty(ViewBag.Message))
                                    {
                                        <div class="alert alert-info">@ViewBag.Message</div>
                                    }
                                </td>
                            </tr>
                        }
                    }
                }
            </tbody>
        </table>
    </div>
</div>